### ISSUE TITLE
Error Message in Logs When Establishing New Session

### ISSUE THREAD

**Issue by gawindx** [gawindx/homebridge-risco-alarm#4]
@andyblac

As you can see, I activated the 'Issue' section.

I refer the problem that you encounter on the error messages during the expiration of a RiscoCloud session.
A priori, the method I used is not 100% reliable, I'll have to see that again.

The original post is [here.](https://github.com/gawindx/homebridge-risco-alarm/pull/2#issuecomment-544251496)

**Comment by andyblac** [comment]
I have enabled debug session in my Homebridge logs, I'll post once I see error again, it takes a few hours for the error to show.

**Comment by gawindx** [comment]
I just pushed an update that should solve the problem.

In the other news / bug fix:
- Better Management of KeepAlive / Expired Session / Re-connection
- When the system is already armed and you want to switch to another arming mode (partial total for example), this is not possible on the RiscoCloud interface and therefore causes a failure => an intermediate disarmament has been put in place to make it possible to switch from one arming mode to another in a transparent way.
- In case of arming failure, the condition of the accessory is always updated and therefore does not correspond to reality => this failure is taken into account in the arming procedure and the state of the accessory is correctly recorded.
- Added a variable to prevent the unexpected error at start-up (slows down the startup of accessories in relation to the session)
- Accessory polling has been reduced to 1 sec to postpone the new state as soon as the session is updated.
- Added many debug messages (be careful, this could increase the size of the log file).
- To retrieve Remote Panel Updates, we will now use the 'GetCPState' request which contains data only when a state change occurs on the Panel.
Only the output status will be parse from the web page.

**Comment by andyblac** [comment]
got it loaded, anything you want to me test ?

**Comment by gawindx** [comment]
No test in particular.
Use it normally and tell me if problems occur.

Theoretically it should not be the case but ...

**Comment by andyblac** [comment]
been running fine lately.

**Comment by gawindx** [comment]
@andyblac 
Sorry for not answering earlier, but I really have not had the time in recent weeks.

Glad that the code works correctly on your side.

I just updated the code with new features like:
- group management in addition to partitions
- the correct ratio of the state of the partition during a timed arming (including in the case of a configuration without polling)
- Correct report of the state of the system after an arming failure

If you want to test on your side and go occasionally

**Comment by andyblac** [comment]
@gawindx 
I don't have any groups, but I have loaded it, will test on my setup.

**Comment by gawindx** [comment]
@andyblac 

Following the abandonment of development by szlaskidaniel and advancement on my side, I abandon this repositorie in favor of a new 'homebridge-risco-platform'.
This new repositorie will lead to the creation of an npm which will simplify the installation of the Risco-Platform on homebridge.

Before long, I will pass 'homebridge-risco-alarm' in private and I invite you to follow the evolution since the new repositorie.
I will do the switch once the npm is created and, in any case, it will not be done before April 21, date of update of RiscoCloud in version 5.3.

If a modification is necessary with this new version of RiscoCloud, it will be applied to the 2 repositories.

**Comment by andyblac** [comment]
hi, good to here from you, hope you are keeping safe, that sounds great here is my email incase your need andyblac@icloud.com. give me a should when it all live,

**Comment by gawindx** [comment]
No worries, we go out as little as possible
I'll let you know when everything is good.

And I hope that health is also good on your side during this somewhat "complicated" period.

**Comment by andyblac** [comment]
just swapped over to the new git, all seems to be working 👍

**Comment by zeroco84** [comment]
Hi gawindx, installed this plugin but getting a username/password mismatch, password is correct. Have created a new master account on riscocloud to see if it was that but same issue.  Any ideas what could cause this?

**Comment by andyblac** [comment]
are you using code from github ?

**Comment by andyblac** [comment]
use the https://github.com/gawindx/homebridge-risco-alarm/tree/RiscoPanel-Platforms branch

**Comment by zeroco84** [comment]
Hey, thanks.  I'm quite inexperienced, so had installed the code via npm.

**Comment by zeroco84** [comment]
Andy thanks, I think I'm a little out of my depth here in trying to get this going.  I've followed the instructions on the RiscoPanel-Platforms page but not seeing anything in the logs.  Do I have to manually edit the plugin? Would appreciate any help going :)
