### ISSUE TITLE
Arming seems to have issue...

### ISSUE THREAD

**Issue by andyblac** [gawindx/homebridge-risco-alarm#5]
in my alarm I have 2 partitions 0 = `Castle Int Alarm` and 1 = `Garage`. ID 0 has a 30 second count down timer, ID 1 does not.

when setting partition 1, things seem to work fine, but when I set partition 0 setting to AWAY (from DISARM) HomeKit seem to give me 3 notifications see attached. I get a ARM, then a few seconds later a DISARM, then after the timeout has finished I get a 3rd ARM.

also a few times the ARM failed to set (maybe due to the disarm). early this morning it took 2 attempts to ARM (3:44:30 & 3:45:58) before it actually ARMED the alarm.

I have attach my syslog and a snapshot of notifications.

[syslog.txt.zip](https://github.com/gawindx/homebridge-risco-alarm/files/3754641/syslog.txt.zip)
![IMG_0519 (1)](https://user-images.githubusercontent.com/77936/67280329-d670e100-f4c4-11e9-97bd-a6b87ab88a82.jpeg)

**Comment by andyblac** [comment]
@gawindx any ideas.

**Comment by gawindx** [comment]
Sorry, I was pretty busy and did not pay attention.

I have set up a security to ensure automatic disarming when the system goes from one partial or complete state to another (except when disarming or already disarmed).

But looking at your logs, I do not see the lines that will indicate that an intermediate and automatic disarmament has been executed.

I will try to reproduce on my side with my panel.

**Comment by andyblac** [comment]
thanks, does not happen on zero count down, only when panel has a count down before arming.

**Comment by andyblac** [comment]
it seems in iOS 13.2 this is no longer the case.

**Comment by gawindx** [comment]
I have not tested with this version, but I am currently seeing to take into account the arming delays. This should definitely correct this behavior.
I hope to be able to deploy the features soon but I am afraid I will run out of time this week.

**Comment by andyblac** [comment]
thanks for working on this plugin.
